import {
  siArtstation,
  siBlender,
  siBootstrap,
  siCss,
  siExpress,
  siFigma,
  siHtml5,
  siInstagram,
  siJavascript,
  siMongodb,
  siNextdotjs,
  siNodedotjs,
  siPinterest,
  siReact,
  siTailwindcss,
  siTypescript,
  siX,
} from "simple-icons";

export const admin = {
  name: "Ashwin Kumar",
  email: "code.by.ashwin@gmail.com",
  links: {
    github: "https://github.com/ashwnkumar",
    linkedin: "https://www.linkedin.com/in/ashwin-kumar-221160240",
  },
  profile: "/assets/home.jpg",
  aboutProfile: "/assets/about.jpg",
  socialLinks: [
    {
      title: "Instagram",
      link: "https://www.instagram.com/ashwnkumar/",
      icon: siInstagram,
      color: "#FD006C",
    },
    {
      title: "X",
      link: "https://www.instagram.com/ashwnkumaar/",
      icon: siX,
      color: "#000000",
    },
    {
      title: "Pinterest",
      link: "https://www.linkedin.com/in/ashwin-kumar-221160240",
      icon: siPinterest,
      color: "#e70025",
    },
    {
      title: "ArtStation",
      link: "https://www.artstation.com/ashwnkumar/",
      icon: siArtstation,
      color: "#42A5F5",
    },
  ],
  aboutShort: `

  A Full Stack Web Developer,<span class="text-secondary"> specializing in 
  creating clean, user-focused web interfaces <span/> .
`,
  location: "Pune, Maharashtra, India",
  stack: [
    { name: "ReactJS", icon: siReact },
    { name: "NextJS", icon: siNextdotjs },
    { name: "MongoDB", icon: siMongodb },
    { name: "ExpressJS", icon: siExpress },
    { name: "NodeJS", icon: siNodedotjs },
    { name: "React Native", icon: siReact },
    { name: "JavaScript", icon: siJavascript },
    { name: "TypeScript", icon: siTypescript },
    { name: "Figma", icon: siFigma },
    { name: "HTML", icon: siHtml5 },
    { name: "CSS", icon: siCss },
    { name: "TailwindCSS", icon: siTailwindcss },
    { name: "Bootstrap", icon: siBootstrap },
    { name: "Blender", icon: siBlender },
  ],
  workExp: [
    {
      id: "ndss",
      company: "NDSoftTech Solutions",
      position: "SDE - Trainee",
      from: "Jul 2025",
      work: [
        "Developed user facing interfaces using React Native for multiple applications.",
        "Optimized codebase readability by introducing reusable components.",
        "Worked with backend database and transformed data in various way to fetch useful data from the backend.",
      ],
      skills: [
        "ReactJS",
        "NodeJS",
        "JavaScript",
        "Express.js",
        "MongoDB",
        "NodeJS",
        "React Native",
        "TailwindCSS",
      ],
    },
    {
      id: "dreams",
      company: "Dreams International Pvt. Ltd.",
      position: "ReactJS Intern",
      from: "Nov 2024",
      to: "May 2025",
      work: [
        "Participated in end-to-end project development—from initial coding to final deployment—ensuring reliable performance in production environments.",
        "Developed numerous reusable React components to accelerate development and maintain a clean, scalable codebase.",
        "Took charge of complete UI redesigns for multiple projects, improving how they looked, felt, and performed.",
        "Worked closely with design teams and backend engineers to turn concepts into functional, polished web applications.",
      ],
      skills: ["ReactJS", "Axios", "JavaScript", "Figma", "TailwindCSS", "CSS"],
    },
  ],
};
