// Regenerates lib/devicon-list.ts from devicon's official manifest.
//
//   npm run icons:refresh
//
// devicon publishes devicon.json, so keeping the picker current is one fetch
// of one file — no scraping, no API key, no button in the admin that cannot
// write to the filesystem anyway.
import fs from "node:fs";
import path from "node:path";

const MANIFEST = "https://raw.githubusercontent.com/devicons/devicon/master/devicon.json";
const OUT = path.join(process.cwd(), "lib", "devicon-list.ts");

// Prefer a full-colour mark; fall back through devicon's other variants.
const VARIANT_ORDER = ["original", "plain", "line", "original-wordmark", "plain-wordmark", "line-wordmark"];

const res = await fetch(MANIFEST);
if (!res.ok) {
  console.error(`Failed to fetch devicon.json (${res.status})`);
  process.exit(1);
}
const manifest = await res.json();

const icons = manifest
  .map((entry) => {
    const svg = entry.versions?.svg ?? [];
    const variant = VARIANT_ORDER.find((v) => svg.includes(v)) ?? svg[0];
    if (!variant) return null;
    return {
      id: entry.name,
      variant,
      // altnames catch things like "vuejs" for "vue"; tags catch "framework".
      terms: [...new Set([...(entry.altnames ?? []), ...(entry.tags ?? [])])].join(" "),
    };
  })
  .filter(Boolean)
  .sort((a, b) => a.id.localeCompare(b.id));

const previous = fs.existsSync(OUT)
  ? (fs.readFileSync(OUT, "utf8").match(/\/\/ count: (\d+)/)?.[1] ?? null)
  : null;

fs.writeFileSync(
  OUT,
  `// GENERATED by scripts/refresh-icons.mjs — do not edit by hand.
// Source: ${MANIFEST}
// count: ${icons.length}

export type DeviconEntry = {
  /** devicon icon name, stored in skills.icon_id */
  id: string;
  /** devicon variant, stored in skills.icon_variant */
  variant: string;
  /** extra search terms (altnames + tags) */
  terms: string;
};

export const DEVICON_ICONS: DeviconEntry[] = ${JSON.stringify(icons, null, 0)};
`,
);

console.log(`wrote lib/devicon-list.ts — ${icons.length} icons${previous ? ` (was ${previous})` : ""}`);
